# Generated by Django 5.1.1 on 2024-10-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
