# # Generated by Django 5.1.1 on 2024-10-07 20:00

# import uuid
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ("api", "0003_remove_user_role"),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name="user",
#             name="is_verified",
#             field=models.BooleanField(default=False),
#         ),
#         migrations.AddField(
#             model_name="user",
#             name="role",
#             field=models.CharField(
#                 choices=[("student", "Student"), ("landlord", "Landlord")],
#                 default="student",
#                 max_length=20,
#             ),
#         ),
#         migrations.AddField(
#             model_name="user",
#             name="verification_token",
#             field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
#         ),
#     ]
# Generated by Django 5.1.1 on 2024-10-07 20:00

import uuid
from django.db import migrations, models


def generate_verification_token(apps, schema_editor):
    User = apps.get_model("api", "User")  # 'api' is your app name
    for user in User.objects.all():
        if not user.verification_token:  # Ensure no existing token is overwritten
            user.verification_token = uuid.uuid4()
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("landlord", "Landlord")],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(
            generate_verification_token
        ),  # This will generate tokens for existing users
    ]
