# Generated by Django 5.1.1 on 2024-10-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_is_verified_user_role_user_verification_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Property",
        ),
    ]
